// <auto-generated />
using System;
using HappierFarm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappierFarm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520141524_FootprintsExpansionDecorations")]
    partial class FootprintsExpansionDecorations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HappierFarm.Domain.Entities.AnimalDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<int>("FootprintHeight")
                        .HasColumnType("int");

                    b.Property<int>("FootprintWidth")
                        .HasColumnType("int");

                    b.Property<int>("MaxOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<int>("MaxPlaced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductionIntervalSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnimalDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPrice = 150,
                            FootprintHeight = 1,
                            FootprintWidth = 2,
                            MaxOwned = 4,
                            MaxPlaced = 4,
                            Name = "Happy Holstein",
                            ProductCode = "milk",
                            ProductQuantity = 2,
                            ProductionIntervalSeconds = 90
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.CropDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseYield")
                        .HasColumnType("int");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<int>("GrowthDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SellValue")
                        .HasColumnType("int");

                    b.Property<int>("XpReward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CropDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseYield = 1,
                            BuyPrice = 10,
                            GrowthDurationSeconds = 60,
                            Name = "Sunny Barley",
                            SellValue = 28,
                            XpReward = 5
                        },
                        new
                        {
                            Id = 2,
                            BaseYield = 1,
                            BuyPrice = 20,
                            GrowthDurationSeconds = 120,
                            Name = "Swift Carrot",
                            SellValue = 55,
                            XpReward = 12
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.DecorationDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<int>("FootprintHeight")
                        .HasColumnType("int");

                    b.Property<int>("FootprintWidth")
                        .HasColumnType("int");

                    b.Property<int>("MaxOwned")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlaced")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("DecorationDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPrice = 35,
                            FootprintHeight = 1,
                            FootprintWidth = 1,
                            MaxOwned = 30,
                            MaxPlaced = 30,
                            Name = "Sunflower Patch"
                        },
                        new
                        {
                            Id = 2,
                            BuyPrice = 60,
                            FootprintHeight = 1,
                            FootprintWidth = 2,
                            MaxOwned = 20,
                            MaxPlaced = 20,
                            Name = "Wooden Fence"
                        },
                        new
                        {
                            Id = 3,
                            BuyPrice = 45,
                            FootprintHeight = 1,
                            FootprintWidth = 1,
                            MaxOwned = 30,
                            MaxPlaced = 30,
                            Name = "Cozy Hay Bale"
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FactoryDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<int>("FootprintHeight")
                        .HasColumnType("int");

                    b.Property<int>("FootprintWidth")
                        .HasColumnType("int");

                    b.Property<int>("InputQuantity")
                        .HasColumnType("int");

                    b.Property<string>("InputResourceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("MaxOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("MaxPlaced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("int");

                    b.Property<string>("OutputResourceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ProcessSeconds")
                        .HasColumnType("int");

                    b.Property<int>("SellValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FactoryDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPrice = 220,
                            FootprintHeight = 2,
                            FootprintWidth = 2,
                            InputQuantity = 3,
                            InputResourceCode = "milk",
                            MaxOwned = 2,
                            MaxPlaced = 2,
                            Name = "Meadow Cheese Press",
                            OutputQuantity = 1,
                            OutputResourceCode = "cheese",
                            ProcessSeconds = 45,
                            SellValue = 80
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FarmPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<int>("FootprintHeight")
                        .HasColumnType("int");

                    b.Property<int>("FootprintWidth")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("LastActionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "CoordinateX", "CoordinateY")
                        .IsUnique();

                    b.ToTable("FarmPlacements", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FarmTile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<int?>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PlantedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.HasIndex("PlayerId", "CoordinateX", "CoordinateY")
                        .IsUnique();

                    b.ToTable("FarmTiles", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastCollectedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("PlayerId", "AnimalTypeId")
                        .IsUnique();

                    b.ToTable("PlayerAnimals", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerDecoration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DecorationTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DecorationTypeId");

                    b.HasIndex("PlayerId", "DecorationTypeId")
                        .IsUnique();

                    b.ToTable("PlayerDecorations", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerFactory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FactoryTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastProcessedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactoryTypeId");

                    b.HasIndex("PlayerId", "FactoryTypeId")
                        .IsUnique();

                    b.ToTable("PlayerFactories", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ResourceCode")
                        .IsUnique();

                    b.ToTable("PlayerResources", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerSeedStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.HasIndex("PlayerId", "CropTypeId")
                        .IsUnique();

                    b.ToTable("PlayerSeedStocks", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameNormalized")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<int>("FarmGridSize")
                        .HasColumnType("int");

                    b.Property<int>("GoldCoins")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayNameNormalized")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FarmPlacement", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FarmTile", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.CropDefinition", "CropType")
                        .WithMany()
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerAnimal", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.AnimalDefinition", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerDecoration", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.DecorationDefinition", "DecorationType")
                        .WithMany()
                        .HasForeignKey("DecorationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecorationType");
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerFactory", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.FactoryDefinition", "FactoryType")
                        .WithMany()
                        .HasForeignKey("FactoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryType");
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerResource", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerSeedStock", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.CropDefinition", "CropType")
                        .WithMany()
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
