// <auto-generated />
using System;
using HappierFarm.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappierFarm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527081901_SeedArabicCatalogDisplayNames")]
    partial class SeedArabicCatalogDisplayNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HappierFarm.Domain.Entities.AnimalDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FeedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("FeedResourceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("FootprintHeight")
                        .HasColumnType("int");

                    b.Property<int>("FootprintWidth")
                        .HasColumnType("int");

                    b.Property<int>("MaxOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<int>("MaxPlaced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4);

                    b.Property<int>("MinLevelRequired")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductionIntervalSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AnimalDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPrice = 250,
                            DisplayNameAr = "بقرة هولشتاين سعيدة",
                            DisplayNameEn = "Happy Holstein",
                            FeedQuantity = 2,
                            FeedResourceCode = "wheat",
                            FootprintHeight = 1,
                            FootprintWidth = 2,
                            MaxOwned = 4,
                            MaxPlaced = 4,
                            MinLevelRequired = 3,
                            Name = "Happy Holstein",
                            ProductCode = "milk",
                            ProductQuantity = 2,
                            ProductionIntervalSeconds = 2700
                        },
                        new
                        {
                            Id = 2,
                            BuyPrice = 200,
                            DisplayNameAr = "خروف صوفي",
                            DisplayNameEn = "Woolly Sheep",
                            FeedQuantity = 2,
                            FeedResourceCode = "barley",
                            FootprintHeight = 1,
                            FootprintWidth = 1,
                            MaxOwned = 4,
                            MaxPlaced = 4,
                            MinLevelRequired = 4,
                            Name = "Woolly Sheep",
                            ProductCode = "wool",
                            ProductQuantity = 2,
                            ProductionIntervalSeconds = 3600
                        },
                        new
                        {
                            Id = 3,
                            BuyPrice = 60,
                            DisplayNameAr = "دجاجة بياض",
                            DisplayNameEn = "Clucking Hen",
                            FeedQuantity = 1,
                            FeedResourceCode = "carrot",
                            FootprintHeight = 1,
                            FootprintWidth = 1,
                            MaxOwned = 6,
                            MaxPlaced = 6,
                            MinLevelRequired = 2,
                            Name = "Clucking Hen",
                            ProductCode = "egg",
                            ProductQuantity = 3,
                            ProductionIntervalSeconds = 1200
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.BarnUpgradeTierDefinition", b =>
                {
                    b.Property<int>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tier"));

                    b.Property<int>("BonusSlots")
                        .HasColumnType("int");

                    b.Property<int>("GoldCost")
                        .HasColumnType("int");

                    b.HasKey("Tier");

                    b.ToTable("BarnUpgradeTierDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Tier = 1,
                            BonusSlots = 20,
                            GoldCost = 250
                        },
                        new
                        {
                            Tier = 2,
                            BonusSlots = 50,
                            GoldCost = 600
                        },
                        new
                        {
                            Tier = 3,
                            BonusSlots = 100,
                            GoldCost = 1500
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.CatalogTimingOverride", b =>
                {
                    b.Property<string>("CatalogKind")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("CatalogId")
                        .HasColumnType("int");

                    b.Property<int>("BaseSeconds")
                        .HasColumnType("int");

                    b.HasKey("CatalogKind", "CatalogId");

                    b.ToTable("CatalogTimingOverrides", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.CropDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseYield")
                        .HasColumnType("int");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("GrowthDurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("HarvestResourceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("MinLevelRequired")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SellValue")
                        .HasColumnType("int");

                    b.Property<int>("XpReward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CropDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseYield = 1,
                            BuyPrice = 8,
                            DisplayNameAr = "شعير مشمس",
                            DisplayNameEn = "Sunny Barley",
                            GrowthDurationSeconds = 1800,
                            HarvestResourceCode = "barley",
                            MinLevelRequired = 1,
                            Name = "Sunny Barley",
                            SellValue = 18,
                            XpReward = 5
                        },
                        new
                        {
                            Id = 2,
                            BaseYield = 1,
                            BuyPrice = 15,
                            DisplayNameAr = "جزر سريع",
                            DisplayNameEn = "Swift Carrot",
                            GrowthDurationSeconds = 2700,
                            HarvestResourceCode = "carrot",
                            MinLevelRequired = 2,
                            Name = "Swift Carrot",
                            SellValue = 35,
                            XpReward = 12
                        },
                        new
                        {
                            Id = 3,
                            BaseYield = 1,
                            BuyPrice = 12,
                            DisplayNameAr = "قمح ذهبي",
                            DisplayNameEn = "Golden Wheat",
                            GrowthDurationSeconds = 2400,
                            HarvestResourceCode = "wheat",
                            MinLevelRequired = 2,
                            Name = "Golden Wheat",
                            SellValue = 28,
                            XpReward = 8
                        },
                        new
                        {
                            Id = 4,
                            BaseYield = 1,
                            BuyPrice = 30,
                            DisplayNameAr = "طماطم متسلقة",
                            DisplayNameEn = "Vine Tomato",
                            GrowthDurationSeconds = 7200,
                            HarvestResourceCode = "tomato",
                            MinLevelRequired = 4,
                            Name = "Vine Tomato",
                            SellValue = 65,
                            XpReward = 18
                        },
                        new
                        {
                            Id = 5,
                            BaseYield = 1,
                            BuyPrice = 45,
                            DisplayNameAr = "يقطين خريفي",
                            DisplayNameEn = "Autumn Pumpkin",
                            GrowthDurationSeconds = 14400,
                            HarvestResourceCode = "pumpkin",
                            MinLevelRequired = 6,
                            Name = "Autumn Pumpkin",
                            SellValue = 110,
                            XpReward = 28
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.DecorationDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FootprintHeight")
                        .HasColumnType("int");

                    b.Property<int>("FootprintWidth")
                        .HasColumnType("int");

                    b.Property<int>("MaxOwned")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlaced")
                        .HasColumnType("int");

                    b.Property<int>("MinLevelRequired")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("DecorationDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPrice = 35,
                            DisplayNameAr = "بستان عباد الشمس",
                            DisplayNameEn = "Sunflower Patch",
                            FootprintHeight = 1,
                            FootprintWidth = 1,
                            MaxOwned = 30,
                            MaxPlaced = 30,
                            MinLevelRequired = 2,
                            Name = "Sunflower Patch"
                        },
                        new
                        {
                            Id = 2,
                            BuyPrice = 60,
                            DisplayNameAr = "سياج خشبي",
                            DisplayNameEn = "Wooden Fence",
                            FootprintHeight = 1,
                            FootprintWidth = 2,
                            MaxOwned = 20,
                            MaxPlaced = 20,
                            MinLevelRequired = 3,
                            Name = "Wooden Fence"
                        },
                        new
                        {
                            Id = 3,
                            BuyPrice = 45,
                            DisplayNameAr = "بالة قش مريحة",
                            DisplayNameEn = "Cozy Hay Bale",
                            FootprintHeight = 1,
                            FootprintWidth = 1,
                            MaxOwned = 30,
                            MaxPlaced = 30,
                            MinLevelRequired = 5,
                            Name = "Cozy Hay Bale"
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FactoryDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyPrice")
                        .HasColumnType("int");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("FootprintHeight")
                        .HasColumnType("int");

                    b.Property<int>("FootprintWidth")
                        .HasColumnType("int");

                    b.Property<int>("InputQuantity")
                        .HasColumnType("int");

                    b.Property<string>("InputResourceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsBarn")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("MaxPlaced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int>("MinLevelRequired")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("OutputQuantity")
                        .HasColumnType("int");

                    b.Property<string>("OutputResourceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ProcessSeconds")
                        .HasColumnType("int");

                    b.Property<int>("SellValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FactoryDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPrice = 220,
                            DisplayNameAr = "مكبس جبن المرج",
                            DisplayNameEn = "Meadow Cheese Press",
                            FootprintHeight = 2,
                            FootprintWidth = 2,
                            InputQuantity = 3,
                            InputResourceCode = "milk",
                            IsBarn = false,
                            MaxOwned = 2,
                            MaxPlaced = 2,
                            MinLevelRequired = 4,
                            Name = "Meadow Cheese Press",
                            OutputQuantity = 1,
                            OutputResourceCode = "cheese",
                            ProcessSeconds = 1800,
                            SellValue = 80
                        },
                        new
                        {
                            Id = 3,
                            BuyPrice = 200,
                            DisplayNameAr = "غزّالة الصوف",
                            DisplayNameEn = "Wool Spinner",
                            FootprintHeight = 2,
                            FootprintWidth = 2,
                            InputQuantity = 2,
                            InputResourceCode = "wool",
                            IsBarn = false,
                            MaxOwned = 2,
                            MaxPlaced = 2,
                            MinLevelRequired = 5,
                            Name = "Wool Spinner",
                            OutputQuantity = 1,
                            OutputResourceCode = "yarn",
                            ProcessSeconds = 2400,
                            SellValue = 45
                        },
                        new
                        {
                            Id = 4,
                            BuyPrice = 280,
                            DisplayNameAr = "مخبز القرية",
                            DisplayNameEn = "Village Bakery",
                            FootprintHeight = 2,
                            FootprintWidth = 2,
                            InputQuantity = 3,
                            InputResourceCode = "wheat",
                            IsBarn = false,
                            MaxOwned = 2,
                            MaxPlaced = 2,
                            MinLevelRequired = 6,
                            Name = "Village Bakery",
                            OutputQuantity = 1,
                            OutputResourceCode = "bread",
                            ProcessSeconds = 3000,
                            SellValue = 55
                        },
                        new
                        {
                            Id = 2,
                            BuyPrice = 350,
                            DisplayNameAr = "حظيرة تخزين",
                            DisplayNameEn = "Hearty Barn",
                            FootprintHeight = 2,
                            FootprintWidth = 2,
                            InputQuantity = 0,
                            InputResourceCode = "none",
                            IsBarn = true,
                            MaxOwned = 1,
                            MaxPlaced = 1,
                            MinLevelRequired = 3,
                            Name = "Hearty Barn",
                            OutputQuantity = 0,
                            OutputResourceCode = "none",
                            ProcessSeconds = 0,
                            SellValue = 0
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FarmPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatchRuns")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<int>("FootprintHeight")
                        .HasColumnType("int");

                    b.Property<int>("FootprintWidth")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("LastActionUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "CoordinateX", "CoordinateY")
                        .IsUnique();

                    b.ToTable("FarmPlacements", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FarmTile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("int");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("int");

                    b.Property<int?>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PlantedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.HasIndex("PlayerId", "CoordinateX", "CoordinateY")
                        .IsUnique();

                    b.ToTable("FarmTiles", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.GameSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbsoluteMaxGridSize")
                        .HasColumnType("int");

                    b.Property<string>("ActiveEventMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActiveEventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActiveEventTimePercent")
                        .HasColumnType("int");

                    b.Property<int>("BarnFactoryTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BaseStorageCapacity")
                        .HasColumnType("int");

                    b.Property<int>("DefaultGridSize")
                        .HasColumnType("int");

                    b.Property<int>("ExpansionAreaTaxPerStepSq")
                        .HasColumnType("int");

                    b.Property<int>("ExpansionBasePrice")
                        .HasColumnType("int");

                    b.Property<double>("ExpansionGrowthRate")
                        .HasColumnType("float");

                    b.Property<int>("GlobalTimePercent")
                        .HasColumnType("int");

                    b.Property<int>("MaxBankedAnimalCycles")
                        .HasColumnType("int");

                    b.Property<int>("MinGridSize")
                        .HasColumnType("int");

                    b.Property<int>("StarterDinars")
                        .HasColumnType("int");

                    b.Property<int>("StarterGold")
                        .HasColumnType("int");

                    b.Property<int>("StoragePerLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbsoluteMaxGridSize = 999,
                            ActiveEventTimePercent = 0,
                            BarnFactoryTypeId = 2,
                            BaseStorageCapacity = 50,
                            DefaultGridSize = 9,
                            ExpansionAreaTaxPerStepSq = 25,
                            ExpansionBasePrice = 450,
                            ExpansionGrowthRate = 2.0800000000000001,
                            GlobalTimePercent = 100,
                            MaxBankedAnimalCycles = 30,
                            MinGridSize = 9,
                            StarterDinars = 100,
                            StarterGold = 100,
                            StoragePerLevel = 10
                        });
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastCollectedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("PlayerId", "AnimalTypeId")
                        .IsUnique();

                    b.ToTable("PlayerAnimals", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerDecoration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DecorationTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DecorationTypeId");

                    b.HasIndex("PlayerId", "DecorationTypeId")
                        .IsUnique();

                    b.ToTable("PlayerDecorations", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerFactory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FactoryTypeId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastProcessedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FactoryTypeId");

                    b.HasIndex("PlayerId", "FactoryTypeId")
                        .IsUnique();

                    b.ToTable("PlayerFactories", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "ResourceCode")
                        .IsUnique();

                    b.ToTable("PlayerResources", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerSeedStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropTypeId");

                    b.HasIndex("PlayerId", "CropTypeId")
                        .IsUnique();

                    b.ToTable("PlayerSeedStocks", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.ResourceDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DisplayNameAr")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SellValue")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("ResourceDefinitions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "barley",
                            Category = "crop",
                            DisplayNameAr = "شعير",
                            DisplayNameEn = "Barley",
                            IsEnabled = true,
                            SellValue = 28,
                            SortOrder = 10
                        },
                        new
                        {
                            Code = "carrot",
                            Category = "crop",
                            DisplayNameAr = "جزر",
                            DisplayNameEn = "Carrot",
                            IsEnabled = true,
                            SellValue = 55,
                            SortOrder = 20
                        },
                        new
                        {
                            Code = "wheat",
                            Category = "crop",
                            DisplayNameAr = "قمح",
                            DisplayNameEn = "Wheat",
                            IsEnabled = true,
                            SellValue = 38,
                            SortOrder = 30
                        },
                        new
                        {
                            Code = "tomato",
                            Category = "crop",
                            DisplayNameAr = "طماطم",
                            DisplayNameEn = "Tomato",
                            IsEnabled = true,
                            SellValue = 72,
                            SortOrder = 40
                        },
                        new
                        {
                            Code = "pumpkin",
                            Category = "crop",
                            DisplayNameAr = "يقطين",
                            DisplayNameEn = "Pumpkin",
                            IsEnabled = true,
                            SellValue = 120,
                            SortOrder = 50
                        },
                        new
                        {
                            Code = "milk",
                            Category = "animal_product",
                            DisplayNameAr = "حليب",
                            DisplayNameEn = "Milk",
                            IsEnabled = true,
                            SellValue = 12,
                            SortOrder = 60
                        },
                        new
                        {
                            Code = "egg",
                            Category = "animal_product",
                            DisplayNameAr = "بيض",
                            DisplayNameEn = "Egg",
                            IsEnabled = true,
                            SellValue = 8,
                            SortOrder = 70
                        },
                        new
                        {
                            Code = "wool",
                            Category = "animal_product",
                            DisplayNameAr = "صوف",
                            DisplayNameEn = "Wool",
                            IsEnabled = true,
                            SellValue = 18,
                            SortOrder = 80
                        },
                        new
                        {
                            Code = "cheese",
                            Category = "factory_product",
                            DisplayNameAr = "جبن",
                            DisplayNameEn = "Cheese",
                            IsEnabled = true,
                            SellValue = 80,
                            SortOrder = 90
                        },
                        new
                        {
                            Code = "yarn",
                            Category = "factory_product",
                            DisplayNameAr = "غزل",
                            DisplayNameEn = "Yarn",
                            IsEnabled = true,
                            SellValue = 45,
                            SortOrder = 100
                        },
                        new
                        {
                            Code = "bread",
                            Category = "factory_product",
                            DisplayNameAr = "خبز",
                            DisplayNameEn = "Bread",
                            IsEnabled = true,
                            SellValue = 55,
                            SortOrder = 110
                        });
                });

            modelBuilder.Entity("HappierFarm.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("BarnUpgradeTier")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Dinars")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayNameNormalized")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<int>("FarmGridSize")
                        .HasColumnType("int");

                    b.Property<int>("GoldCoins")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayNameNormalized")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FarmPlacement", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.FarmTile", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.CropDefinition", "CropType")
                        .WithMany()
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerAnimal", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.AnimalDefinition", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerDecoration", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.DecorationDefinition", "DecorationType")
                        .WithMany()
                        .HasForeignKey("DecorationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecorationType");
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerFactory", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.FactoryDefinition", "FactoryType")
                        .WithMany()
                        .HasForeignKey("FactoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FactoryType");
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerResource", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HappierFarm.Domain.Entities.PlayerSeedStock", b =>
                {
                    b.HasOne("HappierFarm.Domain.Entities.CropDefinition", "CropType")
                        .WithMany()
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HappierFarm.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
